# Generated by Django 6.0.5 on 2026-05-26 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('game_type', models.CharField(choices=[('puzzle', '🧩 Rompecabezas'), ('story', '📖 Cuento'), ('consonants', '🔤 Consonantes'), ('numbers', '🔢 Números'), ('math_add', '➕ Sumas'), ('math_sub', '➖ Restas'), ('signs', '🤟 Lenguaje de Señas'), ('drawing', '🎨 Dibujo Libre')], max_length=20)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='games/')),
                ('is_active', models.BooleanField(default=True)),
                ('stars_reward', models.PositiveIntegerField(default=3)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Juego',
                'verbose_name_plural': 'Juegos',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('stars_earned', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='games.game')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Juego',
                'verbose_name_plural': 'Sesiones de Juego',
                'ordering': ['-started_at'],
            },
        ),
    ]
