# Generated by Django 4.2.30 on 2026-05-27 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0002_puzzle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('puzzle', '🧩 Rompecabezas'), ('coloring', '🖍️ Colorear'), ('story', '📖 Cuento'), ('consonants', '🔤 Consonantes'), ('numbers', '🔢 Números'), ('math_add', '➕ Sumas'), ('math_sub', '➖ Restas'), ('signs', '🤟 Lenguaje de Señas'), ('drawing', '🎨 Dibujo Libre')], max_length=20),
        ),
        migrations.CreateModel(
            name='ColoringImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='coloring_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coloring_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imagen para Colorear',
                'verbose_name_plural': 'Imágenes para Colorear',
                'ordering': ['-created_at'],
            },
        ),
    ]
