# Generated by Django 4.2.30 on 2026-05-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_add_snake_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('puzzle', '🧩 Rompecabezas'), ('coloring', '🖍️ Colorear'), ('story', '📖 Cuento'), ('consonants', '🔤 Consonantes'), ('numbers', '🔢 Números'), ('math_add', '➕ Sumas'), ('math_sub', '➖ Restas'), ('signs', '🤟 Lenguaje de Señas'), ('drawing', '🎨 Dibujo Libre'), ('snake', '🐍 Serpiente'), ('wordsearch', '🔠 Sopa de Letras')], max_length=20),
        ),
    ]
