# Generated by Django 6.0.5 on 2026-05-26 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('announcement_type', models.CharField(choices=[('info', '💬 Información'), ('reminder', '⏰ Recordatorio'), ('important', '🔴 Importante'), ('celebration', '🎉 Celebración')], default='info', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FameBoardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='fame_board/')),
                ('medal_type', models.CharField(choices=[('gold', '🥇 Oro'), ('silver', '🥈 Plata'), ('bronze', '🥉 Bronce'), ('star', '⭐ Estrella'), ('heart', '❤️ Corazón'), ('rainbow', '🌈 Arcoíris')], default='star', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fame_entries', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fame_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salón de la Fama',
                'verbose_name_plural': 'Entradas — Salón de la Fama',
                'ordering': ['-created_at'],
            },
        ),
    ]
