# Generated by Django 6.0.5 on 2026-05-26 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Área/Materia')),
                ('period', models.CharField(max_length=50, verbose_name='Período')),
                ('grade', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Nota')),
                ('performance', models.CharField(choices=[('S', '🌟 Superior'), ('A', '😊 Alto'), ('B', '🙂 Básico'), ('L', '📚 En Proceso')], max_length=2)),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('emotional_progress', models.CharField(blank=True, max_length=200, verbose_name='Progreso emocional')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_records', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Plantilla de Notas',
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='Inicio de semana')),
                ('week_end', models.DateField(verbose_name='Fin de semana')),
                ('creativity_score', models.PositiveSmallIntegerField(default=5, verbose_name='Creatividad')),
                ('behavior_score', models.PositiveSmallIntegerField(default=5, verbose_name='Comportamiento')),
                ('progress_score', models.PositiveSmallIntegerField(default=5, verbose_name='Progreso')),
                ('participation_score', models.PositiveSmallIntegerField(default=5, verbose_name='Participación')),
                ('attendance_score', models.PositiveSmallIntegerField(default=5, verbose_name='Asistencia')),
                ('observations', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True, verbose_name='Logros')),
                ('recommendations', models.TextField(blank=True, verbose_name='Recomendaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte Semanal',
                'verbose_name_plural': 'Reportes Semanales',
                'ordering': ['-week_start'],
            },
        ),
    ]
