# Generated by Django 6.0.5 on 2026-05-26 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('colorear', '🎨 Colorear'), ('puntillismo', '✏️ Puntillismo'), ('rompecabezas', '🧩 Rompecabezas'), ('cuento', '📚 Cuento Interactivo'), ('dibujo_libre', '✍️ Dibujo Libre'), ('consonantes', '🔤 Consonantes'), ('numeros', '🔢 Números 1-100'), ('sumas', '➕ Sumas'), ('restas', '➖ Restas'), ('lenguaje_senas', '🤟 Lenguaje de Señas'), ('exploracion', '🔭 Exploración'), ('actividad_libre', '⭐ Actividad Libre')], max_length=50, unique=True)),
                ('icon', models.CharField(default='⭐', max_length=10)),
                ('color', models.CharField(default='#FF6B6B', max_length=7)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, '⭐ Muy Fácil'), (2, '⭐⭐ Fácil'), (3, '⭐⭐⭐ Medio'), (4, '⭐⭐⭐⭐ Difícil'), (5, '⭐⭐⭐⭐⭐ Muy Difícil')], default=1, verbose_name='Dificultad')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicada'), ('archived', 'Archivada')], default='draft', max_length=20)),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha límite')),
                ('reward_stars', models.PositiveIntegerField(default=3, verbose_name='Estrellas de recompensa')),
                ('reward_sticker', models.CharField(default='star', max_length=50, verbose_name='Sticker de recompensa')),
                ('instructions', models.TextField(blank=True, verbose_name='Instrucciones adicionales')),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/')),
                ('assigned_to_all', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_students', models.ManyToManyField(blank=True, related_name='assigned_activities', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_activities', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='activities.activitycategory')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='activity_attachments/')),
                ('file_type', models.CharField(choices=[('image', 'Imagen'), ('pdf', 'PDF'), ('video', 'Video'), ('audio', 'Audio')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='activities.activity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivitySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('submitted', 'Enviada'), ('reviewed', 'Revisada'), ('approved', '¡Aprobada! ⭐')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField(blank=True)),
                ('drawing_data', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='submissions/')),
                ('teacher_feedback', models.TextField(blank=True)),
                ('stars_awarded', models.PositiveIntegerField(default=0)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False, verbose_name='En salón de la fama')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='activities.activity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Envío',
                'verbose_name_plural': 'Envíos',
                'unique_together': {('activity', 'student')},
            },
        ),
    ]
